runtime: nodejs20

env_variables:
  NODE_ENV: production
  PORT: 8080
  # Discord Bot設定（環境変数で設定）
  # DISCORD_TOKEN: "your_discord_bot_token"
  # DISCORD_GUILD_ID: "your_guild_id"
  # DISCORD_CHANNEL_ID: "your_channel_id"
  # CLIENT_ID: "your_client_id"

automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.6
