steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/my-repo/test-customer-bot:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/my-repo/test-customer-bot:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'test-customer-bot',
           '--image', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/my-repo/test-customer-bot:latest',
           '--region', 'asia-northeast1',
           '--platform', 'managed',
           '--allow-unauthenticated']
